import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatboxProvider, ChatboxLayout } from "@/components/chatbox";
import { BusinessSuggestionProvider } from "@/contexts";
import { PlanSettingsProvider } from "@/contexts/PlanSettingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-force-light="true"
      >
        <ChatboxProvider>
          <BusinessSuggestionProvider>
            <PlanSettingsProvider>
              <ChatboxLayout position="right" width="19.2rem">
                {children}
              </ChatboxLayout>
            </PlanSettingsProvider>
          </BusinessSuggestionProvider>
        </ChatboxProvider>
      </body>
    </html>
  );
}
